[package]
name = "cellular-automata"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.0"

egui = "0.23.0"

eframe = { version = "0.31.1", features = [
    "default",
    "__screenshot", # __screenshot is so we can dump a screenshot using EFRAME_SCREENSHOT_TO
] }